API_DOC/Pages/Document/AdminEditSite.cshtml.cs
using API_DOC.Data;
using API_DOC.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace API_DOC.Pages.Document ;

    public class AdminEditSite : PageModel
    {
        [BindProperty(SupportsGet = true, Name = "InputMethod")]
        public string InputMethod { get; set; }
        [BindProperty]
        public Method Input { get; set; }
        public Method CurrentMethod { get; set; }
        public int MethodCount { get; set; }
        public List<Method?> MethodList { get; set; }
        public UserModel? CurrentUser { get; set; }
        public MethodDb MethodControl{ get; set; }
        public UserDb UserControl{ get; set; }
        public readonly AppDbContext Context;
        
        public AdminEditSite(AppDbContext context)
        {
            Context = context;
        }
        
        public void OnGet()
        {
            MethodControl = new MethodDb(Context, Request);
            UserControl =  new UserDb(Context, Request);
            MethodList = MethodControl.GetMethodList();
            MethodCount = MethodList.Count;
            CurrentUser = UserControl.UserByToken() ?? null;
            if (InputMethod != "Home" && InputMethod != "Dictionary")
            {
                CurrentMethod = MethodControl.GetMethod(InputMethod);
            }
            MethodList = MethodControl.GetMethodList();
            MethodCount = MethodList.Count;
        }
        
        public IActionResult OnPostEdit()
        {
            MethodControl = new MethodDb(Context, Request);
            if (ModelState.IsValid)
            {
                MethodControl.ChangeData(InputMethod, Input);
                return Redirect($"/Document/{Input.Name}");
            }

            // Model is not valid, redisplay the page with validation errors
            return Redirect("/Document");
        }
        
        public IActionResult OnPostNew()
        {
            MethodControl = new MethodDb(Context, Request);
            if (ModelState.IsValid)
            {
                MethodControl.AddData(Input);
                return Redirect($"/Document/{Input.Name}");
            }

            // Model is not valid, redisplay the page with validation errors
            return Redirect("/Document");
        }
    }

API_DOC/Pages/Document/AdminPanel.cshtml.cs
using API_DOC.Data;
using API_DOC.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace API_DOC.Pages.Document ;

    public class AdminPanel : PageModel
    {
        [BindProperty(SupportsGet = true, Name = "State")]
        public string State { get; set; } = "";
        public List<UserModel?> UserList { get; set; }
        public Method SelectedMethod { get; set; }
        public int MethodCount { get; set; }
        public List<Method?> MethodList { get; set; }
        public UserModel? CurrentUser { get; set; }
        public MethodDb MethodControl{ get; set; }
        public UserDb UserControl{ get; set; }
        public readonly AppDbContext Context;
        
        public AdminPanel(AppDbContext context)
        {
            Context = context;
        }
        
        public void OnGet()
        {
            MethodControl = new MethodDb(Context, Request);
            UserControl =  new UserDb(Context, Request);
            MethodList = MethodControl.GetMethodList();
            MethodCount = MethodList.Count;
            UserList = UserControl.NotAccepted();
            CurrentUser = UserControl.UserByToken() ?? null;
            
        }

        public void OnPost()
        {
            UserControl =  new UserDb(Context, Request);
            CurrentUser = UserControl.UserByToken() ?? null;
            UserList = UserControl.NotAccepted();
        }
        
        public IActionResult OnPostAccept(string userName)
        {
            UserControl =  new UserDb(Context, Request);
            UserControl.AcceptUser(userName);
            CurrentUser = UserControl.UserByToken() ?? null;
            return Redirect("/Admin/Panel");
        }

        public IActionResult OnPostReject(string userName)
        {
            UserControl =  new UserDb(Context, Request);
            UserControl.RejectUser(userName);
            CurrentUser = UserControl.UserByToken() ?? null;
            return Redirect("/Admin/Panel");
        }
        
        public IActionResult OnPostSelect(string selectedMethod)
        {
            MethodControl = new MethodDb(Context, Request);
            SelectedMethod = MethodControl.GetMethod(selectedMethod);
            return Redirect("/AdminPanel/Panel");
        }
    }

API_DOC/Pages/Document/Document.cshtml.cs
using API_DOC.Data;
using API_DOC.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore.Infrastructure.Internal;

namespace API_DOC.Pages.Document ;

    public class DocumentModel : PageModel
    {
        [BindProperty(SupportsGet = true, Name = "InputString")]
        public string InputString { get; set; }
        public int MethodCount { get; set; }
        public UserModel? CurrentUser { get; set; }
        public Method? CurrentMethod { get; set; }
        public List<Method?> MethodList { get; set; }
        public UserDb UserControl{ get; set; }
        public MethodDb MethodControl{ get; set; }
        public readonly AppDbContext Context;
        public List<string> Languages = Statics.Languages;
        public string[] Key = Statics.Key;
        public string[] Value = Statics.Value;

        public DocumentModel(AppDbContext context)
        {
            Context = context;
        }
        
        public void OnGet()
        {
            UserControl =  new UserDb(Context, Request);
            MethodControl =  new MethodDb(Context, Request);
            CurrentUser = UserControl.UserByToken() ?? null;
            if (InputString != "Home" && InputString != "Dictionary")
            {
                CurrentMethod = MethodControl.GetMethod(InputString);
            }
            MethodList = MethodControl.GetMethodList();
            MethodCount = MethodList.Count;
        }

    }

API_DOC/Pages/Document/EditProfile.cshtml.cs
using System.ComponentModel.DataAnnotations;
using API_DOC.Data;
using API_DOC.Models;
using Humanizer;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using static API_DOC.Pages.Document.Logging;
namespace API_DOC.Pages.Document ;

    public class EditProfile : PageModel
    {
        [BindProperty(SupportsGet = true, Name = "BrandInput")]
        public string BrandInput { get; set; } = "";
        [BindProperty(SupportsGet = true, Name = "State")]
        public string State { get; set; }
        [BindProperty]
        public UserModel Input { get; set; }

        [BindProperty]
        public PassWord MyPass { get; set; }
        public UserModel? CurrentUser { get; set; }
        public UserDb UserControl{ get; set; }
        public List<string> Error { get; set; }
        public readonly AppDbContext Context;
        
        public EditProfile(AppDbContext context)
        {
            Context = context;
        }
        
        public void OnGet()
        {
            if (TempData.TryGetValue("Error", out var list))
            {
                if (list is string[] errs)
                {
                    Error = new List<string>();
                    foreach (var VARIABLE in errs)
                    {
                        Error.Add(VARIABLE);
                    }
                    TempData["Error"] = null;
                }
            }
            UserControl =  new UserDb(Context, Request);
            CurrentUser = UserControl.UserByToken() ?? null;
        }
        
        public IActionResult OnPost()
        {
            UserControl = new UserDb(Context, Request);
            CurrentUser = UserControl.UserByBrandName(BrandInput) ?? null;
            if (ModelState.IsValid)
            {
                if (State.Equals("EditPassword"))
                {
                    if (Statics.PassConditions(MyPass,CurrentUser.Password ))
                    {
                        UserControl.ChangePassword(CurrentUser.Username, MyPass.Current);
                        return Redirect("/Logging/LogIn");
                    }
                    List<string> result = new List<string>();
                    result.Add("تطابق رمز ها یا رمز قبلی دارای ایراد است");
                    TempData["Error"] = result ;
                    return Redirect($"/{BrandInput}/EditPassword");
                }
                else
                {
                    (List<bool> errorBool, List<string> result) = Statics.ProfileConditions(UserControl, Input, CurrentUser.Username);
                    if (!errorBool.Contains(false))
                    {
                        UserControl.ChangeProfile(CurrentUser.Username, Input);
                        return Redirect("/Logging/LogIn");
                    }
                    TempData["Error"] = result ;
                    return Redirect($"/{BrandInput}/EditProfile");
                }
            }
            return Redirect("/none");
        }
    }

API_DOC/Pages/Document/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace API_DOC.Pages.Document ;

    public class IndexDoc : PageModel
    {
        public void OnGet()
        {
            
        }
    }

API_DOC/Pages/Document/KeyMaker.cshtml.cs
using API_DOC.Data;
using API_DOC.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace API_DOC.Pages.Document ;

    public class KeyMaker : PageModel
    {
        [BindProperty(SupportsGet = true, Name = "BrandInput")]
        public string BrandInput { get; set; } = "";
        [BindProperty(SupportsGet = true, Name = "MethodInput")]
        public string MethodInput { get; set; } = "";
        [BindProperty]
        public Dictionary<string, string> Dict { get; set; } = Statics.Dictionary;
        public UserModel? CurrentUser { get; set; }
        public UserDb UserControl{ get; set; }
        public MethodDb MethodControl{ get; set; }
        public int MethodCount { get; set; }
        public Method? CurrentMethod { get; set; }
        public List<Method?> MethodList { get; set; }
        public List<string> Languages = Statics.Languages;
        public readonly AppDbContext Context;
        
        public KeyMaker(AppDbContext context)
        {
            Context = context;
        }

        public void OnGet()
        {
            UserControl =  new UserDb(Context, Request);
            MethodControl =  new MethodDb(Context, Request);
            CurrentUser = UserControl.UserByToken() ?? null;
            if (MethodInput != "Home" && MethodInput != "Dictionary")
            {
                CurrentMethod = MethodControl.GetMethod(MethodInput);
            }
            MethodList = MethodControl.GetMethodList();
            MethodCount = MethodList.Count;
            Dict = GetDict();
        }

        public Dictionary<string, string> GetDict()
        {
            Dictionary<string, string> res = Statics.Dictionary;
            if (TempData.TryGetValue("Dictionary", out var dict))
            {
                if (dict is Dictionary<string, string> receivedDict)
                {
                    res =  receivedDict;
                }
            }
            return res;
        }

        public IActionResult OnPost()
        {
            UserControl =  new UserDb(Context, Request);
            MethodControl =  new MethodDb(Context, Request);
            CurrentUser = UserControl.UserByToken() ?? null;
            if (MethodInput != "Home" && MethodInput != "Dictionary")
            {
                CurrentMethod = MethodControl.GetMethod(MethodInput);
            }
            if (ModelState.IsValid)
            {
                TempData["Dictionary"] = Dict;
                return Redirect($"{CurrentUser.BrandName}");
            }
            return Redirect("/Document");
        }
        
        public List<string> ElementFinder()
        {
            List<string> list = new List<string>();
            foreach (var key in Dict.Keys)
            {
                if (CurrentMethod.Key.Contains($"<{key}>"))
                {
                    list.Add(key);
                }
            }
            return list;
        }
    }
    

API_DOC/Pages/Document/Logging.cshtml.cs
using API_DOC.Data;
using API_DOC.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace API_DOC.Pages.Document ;

    public class Logging : PageModel
    {
        [BindProperty]
        public UserModel Input { get; set; }
        [BindProperty(SupportsGet = true, Name = "State")]
        public string State { get; set; }
        [BindProperty]
        public PassWord MyPass { get; set; }
        public UserModel? CurrentUser { get; set; }
        public UserDb UserControl{ get; set; }
        public List<string> Error { get; set; }
        public readonly AppDbContext Context;
        
        public Logging(AppDbContext dbContext)
        {
            Context = dbContext;
        }

        public void OnGet()
        {
            if (TempData.TryGetValue("Error", out var list))
            {
                if (list is string[] errs)
                {
                    Error = new List<string>();
                    foreach (var VARIABLE in errs)
                    {
                        Error.Add(VARIABLE);
                    }
                    TempData["Error"] = null;
                }
            }
            UserControl =  new UserDb(Context, Request);
            CurrentUser = UserControl.UserByToken() ?? null;
            if (State.Equals("LogOut"))
            {
                CurrentUser = null;
                Response.Cookies.Delete("AuthToken");
            }
        }
        
         
        public IActionResult OnPost()
        {
            UserControl =  new UserDb(Context, Request);
            if (ModelState.IsValid)
            {
                if (State.Equals("LogIn"))
                {
                    UserModel? user = UserControl.UserByLogin(Input);
                    if (user is {Acceptance: true })
                    {
                        var token = Statics.GenerateAuthToken(user);
                        user.Token = token;
                        Context.SaveChanges();

                        Statics.SetAuthCookie(token, Response);
                    
                        return Redirect("/Document");
                    }
                    List<string> result = new List<string>();
                    if (user == null)
                    {
                        result.Add("نام کاربری یا رمز عبور اشتباه است");
                    }else if (!user.Acceptance)
                    {
                        result.Add("اکانت شما در حال بررسی برای تایید است");
                    }
                    TempData["Error"] = result ;
                    return Redirect("/Logging/LogIn");
                }
                else if (State.Equals("Register"))
                {
                    (List<bool> errorBool, List<string> result) = Statics.RegisterConditions(UserControl, Input, MyPass);
                    if (!errorBool.Contains(false))
                    {
                        UserControl.AddUser(Input, MyPass);
                        return Redirect("/Logging/LogIn");
                    }
                    TempData["Error"] = result ;
                    return Redirect("/Logging/Register");
                }
            }
            return Redirect("/none");
            
        }
    }

API_DOC/Pages/Document/AdminEditSite.cshtml
@page "/Admin/{State}/{InputMethod}"
@using Microsoft.AspNetCore.Mvc.TagHelpers
@model API_DOC.Pages.Document.AdminEditSite

@{
    Layout ="Shared/_Layout";
    ViewData["Title"] = "AdminPanel";
}

@if (Model.CurrentUser is {Username: "admin" })
{
    <div class="Main" style="height: @(Model.MethodCount * 50 + 75)px">
        <div class="Main-Content">
            <br/>
            <form class="EditSite" asp-page="AdminEditSite" asp-page-handler=@(Model.InputMethod == "NewMethod" ? "New" : "Edit") method="post">
                <div class="form-group-site">
                    <div class="input-pair">
                        <label asp-for="Input.Name">Name:</label>
                        <input asp-for="Input.Name" type="text" id="Name" name="Name" value="@(Model.InputMethod != "NewMethod" ? Model.CurrentMethod.Name : "")" required><br><br>
                    </div>
                    <div class="input-pair">
                        <label asp-for="Input.PersianName">PersianName:</label>
                        <input asp-for="Input.PersianName" type="text" id="PersianName" name="PersianName" value="@(Model.InputMethod != "NewMethod" ? Model.CurrentMethod.PersianName : "")" required><br><br>
                    </div>
                </div>

                <label asp-for="Input.Details">Details:</label>
                <input asp-for="Input.Details" type="text" id="Details" name="Details" value="@(Model.InputMethod != "NewMethod" ? Model.CurrentMethod.Details : "")" required><br><br>

                <div class="form-group-site">
                    <div class="input-pair">
                        <label asp-for="Input.Key">Key:</label>
                        <textarea asp-for="Input.Key" type="text" id="Key" name="Key" required></textarea>
                    </div>
                    <div class="input-pair">
                        <label asp-for="Input.CsCode">CsCode:</label>
                        <textarea asp-for="Input.CsCode" type="text" id="CsCode" name="CsCode"></textarea>
                    </div>
                </div>

                <div class="form-group-site">
                    <div class="input-pair">
                        <label asp-for="Input.Php1Code">Php1Code:</label>
                        <textarea asp-for="Input.Php1Code" type="text" id="Php1Code" name="Php1Code"></textarea><br><br>
                    </div>
                    <div class="input-pair">
                        <label asp-for="Input.Php2Code">Php2Code:</label>
                        <textarea asp-for="Input.Php2Code" type="text" id="Php2Code" name="Php2Code"></textarea><br><br>

                    </div>
                </div>

                <div class="form-group-site">
                    <div class="input-pair">
                        <label asp-for="Input.PythonCode">PythonCode:</label>
                        <textarea asp-for="Input.PythonCode" type="text" id="PythonCode" name="PythonCode"></textarea><br><br>
                    </div>
                    <div class="input-pair">
                        <label asp-for="Input.NodeJsCode">NodeJsCode:</label>
                        <textarea asp-for="Input.NodeJsCode" type="text" id="NodeJsCode" name="NodeJsCode"></textarea><br><br>
                    </div>
                </div>
                <button type="submit" class="submit-button" style="position:relative; width:98%; top:-30px;margin-top: 10px; "> تایید </button>
                @if (Model.InputMethod != "NewMethod")
                {
                    <script>
                    function humanizeString(inputString) {
                      // Replace HTML entities with their corresponding characters
                      const decodedString = inputString
                        .replace(/&lt;/g, '<')
                        .replace(/&gt;/g, '>')
                        .replace(/&#xD;/g, '')
                        .replace(/&#xA;/g, '\n')
                        .replace(/&#x9;/g, '\t')
                        .replace(/&#x27;/g, '\'')
                        .replace(/&#x2003;/g, '\'')
                        .replace(/&quot;/g, '\"');
                      
                      return decodedString;
                    }
                    var textarea1 = document.getElementById("Key");
                    var textarea2 = document.getElementById("CsCode");
                    var textarea3 = document.getElementById("Php1Code");
                    var textarea4 = document.getElementById("Php2Code");
                    var textarea5 = document.getElementById("PythonCode");
                    var textarea6 = document.getElementById("NodeJsCode");
                    textarea1.value = humanizeString('@Model.CurrentMethod.Key');
                    textarea2.value = humanizeString('@Model.CurrentMethod.CsCode');
                    textarea3.value = humanizeString('@Model.CurrentMethod.Php1Code');
                    textarea4.value = humanizeString('@Model.CurrentMethod.Php2Code');
                    textarea5.value = humanizeString('@Model.CurrentMethod.PythonCode');
                    textarea6.value = humanizeString('@Model.CurrentMethod.NodeJsCode');
                </script>
                }
                else
                {
                    <script>
                        var textarea2 = document.getElementById("CsCode");
                        var textarea3 = document.getElementById("Php1Code");
                        var textarea4 = document.getElementById("Php2Code");
                        var textarea5 = document.getElementById("PythonCode");
                        var textarea6 = document.getElementById("NodeJsCode");
                        textarea2.value = "[not set yet]";
                        textarea3.value = "[not set yet]";
                        textarea4.value = "[not set yet]";
                        textarea5.value = "[not set yet]";
                        textarea6.value = "[not set yet]";
                    </script>
                }
            </form>
        </div>

        <div class="Main-slide" style="height: @(Model.MethodCount * 50 + 75)px">
            @if (Model.InputMethod != "NewMethod")
            {
                <div class="Methode-div-edit" style="top:0; height: 71px;">
                    <a style="font-size: large;text-decoration: none;font-family: Yekan Bakh,serif" asp-page="./AdminPanel" asp-route-State="Panel" title="Main Page">
                        <p style="top:25%;text-align:center" class="SlideText">برگشت به صفحه قبل</p>
                    </a>
                </div>
                @for (var i = 0; i < Model.MethodCount; i++)
                {
                    <div class="Methode-div-edit" style="top:@(i * 50 + 75)px">
                        <a style="font-size: large;text-decoration: none;font-family: Yekan Bakh,serif" asp-page="./AdminEditSite" title="@Model.MethodList[i].Name" asp-route-InputMethod="@Model.MethodList[i].Name">
                            <p class="SlideText" style="color: @(Model.MethodList[i] == Model.CurrentMethod ? "red" : "black")">@Model.MethodList[i].PersianName</p>
                        </a>
                    </div>
                }
            }
            else
            {
                <div class="Methode-div" style="top:0">
                    <a style="font-size: large;text-decoration: none;font-family: Yekan Bakh,serif" asp-page="./AdminPanel" title="Panel" asp-route-State="Panel">
                        <p class="SlideText">پنل پذیرش</p>
                    </a>
                </div>
                <div class="Methode-div" style="top:50px">
                    <a style="font-size: large;text-decoration: none;font-family: Yekan Bakh,serif" asp-page="./AdminEditSite" title="Edit" asp-route-State="Edit", asp-route-InputMethod="GetCustomerByMobile">
                        <p class="SlideText">تغییر اطلاعات سایت</p>
                    </a>
                </div>
                <div class="Methode-div" style="top:100px">
                    <a style="font-size: large;text-decoration: none;font-family: Yekan Bakh,serif" asp-page="./AdminEditSite" title="Edit" asp-route-State="Edit", asp-route-InputMethod="NewMethod">
                        <p class="SlideText" style="color: green">افزورن متد به سایت</p>
                    </a>
                </div>
            }
            
        </div>
    </div>
}
else
{
<h1 style="text-align: center">Not Authorized</h1>
}

API_DOC/Pages/Document/AdminPanel.cshtml
@page "/Admin/{State}"
@using Microsoft.AspNetCore.Mvc.TagHelpers
@model API_DOC.Pages.Document.AdminPanel

@{
    Layout ="Shared/_Layout";
    ViewData["Title"] = "AdminPanel";
}

@if (Model.CurrentUser is {Username: "admin" })
{
    <div class="Main" style="height: 1000px">
        <div class="Main-Content">
            @if (Model.State == "Panel")
            {
                <table>
                    <thead>
                    <tr>
                        <th>نام کاربری</th>
                        <th>شرکت</th>
                        <th>شماره همراه</th>
                        <th>ایمیل</th>
                        <th>تایید کاربری</th>
                        <th>لغو کاربری</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach (var user in Model.UserList)
                    {
                        <tr>
                            <td>@user.Username</td>
                            <td>@user.BrandName</td>
                            <td>@user.Phone</td>
                            <td>@user.Email</td>
                           <td>
                              <form asp-page="AdminPanel" asp-page-handler="Accept" method="post">
                                  <input type="hidden" name="userName" value="@user.Username" />
                                  <button type="submit" class="ARButton" style="color: green">Accept</button>
                              </form>
                           </td>
                           <td>
                               <form asp-page="AdminPanel" asp-page-handler="Reject" method="post">
                                   <input type="hidden" name="userName" value="@user.Username" />
                                   <button type="submit" class="ARButton" style="color: red">Reject</button>
                               </form>
                           </td>
                        </tr>
                    }
                    </tbody>
                </table>
            }
        </div>
        <div class="Main-slide" style="height: 1000px">
            <div class="Methode-div" style="top:0">
                <a style="font-size: large;text-decoration: none;font-family: Yekan Bakh,serif" asp-page="./AdminPanel" title="Panel" asp-route-State="Panel">
                    <p class="SlideText" style="color: @(Model.State == "Panel" ? "green" : "black")">پنل پذیرش</p>
                </a>
            </div>
            <div class="Methode-div" style="top:50px">
                <a style="font-size: large;text-decoration: none;font-family: Yekan Bakh,serif" asp-page="./AdminEditSite" title="Edit" asp-route-State="Edit", asp-route-InputMethod="GetCustomerByMobile">
                    <p class="SlideText">تغییر اطلاعات سایت</p>
                </a>
            </div>
            <div class="Methode-div" style="top:100px">
                <a style="font-size: large;text-decoration: none;font-family: Yekan Bakh,serif" asp-page="./AdminEditSite" title="Edit" asp-route-State="Edit", asp-route-InputMethod="NewMethod">
                    <p class="SlideText">افزودن متد به سایت</p>
                </a>
            </div>
        </div>
    </div>
}
else
{
    <h1 style="text-align: center">Not Authorized</h1>
}

API_DOC/Pages/Document/EditProfile.cshtml
@page "/{BrandInput}/{state}"
@using Microsoft.AspNetCore.Mvc.TagHelpers
@using System.Reflection.Metadata
@model API_DOC.Pages.Document.EditProfile

@{
    Layout = "Shared/_Layout";
    ViewData["Title"] = "Profile";
}
@if (Model.CurrentUser != null && Model.CurrentUser.BrandName.Equals(Model.BrandInput))
{
    @if (Model.Error != null)
    {
        @foreach (var variable in Model.Error)
        {
            <div>@variable</div>
        }
    }
    @if (Model.State.Equals("EditProfile"))
    {<div style="position:relative;width: 100%;height:650px">
        <div style="position:relative; height:600px;width: 340px; left: 50% ; top: 20px; transform: translate(-50%, 0);background-color: #9DC4D9;border-radius: 10px;">
            <div class="login-container">
                <h2 style="text-align: center; color: #333;">تغییر اطلاعات حساب کاربری</h2>
                <form class="login-form" method="post">
                    <div class="form-group">
                        <label asp-for="Input.Username">نام کاربری</label>
                        <input asp-for="Input.Username" value="@Model.CurrentUser?.Username" class="form-control" required>
                    </div>
                    <div class="form-group">
                        <label asp-for="Input.Email">پست الکترونیکی</label>
                        <input asp-for="Input.Email" value="@Model.CurrentUser?.Email" class="form-control" required>
                    </div>
                    <div class="form-group">
                        <label asp-for="Input.Phone">شماره همراه</label>
                        <input asp-for="Input.Phone" value="@Model.CurrentUser?.Phone" class="form-control" required>
                    </div>
                    <div class="form-group">
                        <label asp-for="Input.BrandName">نام شرکت</label>
                        <input asp-for="Input.BrandName" value="@Model.CurrentUser?.BrandName" class="form-control" required>
                    </div>
                    <button type="submit" class="submit-button">تغییر اطلاعات</button>
                </form>
                <a asp-page="./EditProfile" asp-route-BrandInput="@Model.CurrentUser.BrandName" asp-route-State="EditPassword" style="text-decoration: none">
                    <button class="submit-button" style="margin-top: 10px">تغییر رمز </button>
                </a>
            </div>
        </div>
    </div>
    }
    else if(Model.State.Equals("EditPassword"))
    {
        <div style="position:relative;width: 100%;height:540px">
            <div style="position:relative; height:490px;width: 340px; left: 50% ; top: 20px; transform: translate(-50%, 0);background-color: #9DC4D9;border-radius: 10px;">
                <div class="login-container">
                    <h2 style="text-align: center; color: #333;">تغییر اطلاعات حساب کاربری</h2>
                    <form class="login-form" method="post">
                        <div class="form-group">
                            <label asp-for="MyPass.Past">رمز عبور قبلی</label>
                            <input asp-for="MyPass.Past" type="password" class="form-control" required>
                        </div>
                        <div class="form-group">
                            <label asp-for="MyPass.Current">رمز عبور جدید</label>
                            <input asp-for="MyPass.Current" type="password" class="form-control" required>
                        </div>
                        <div class="form-group">
                            <label asp-for="MyPass.Confirm">تکرار رمز عبور جدید</label>
                            <input asp-for="MyPass.Confirm" type="password" class="form-control" required>
                        </div>
                        <button type="submit" class="submit-button">تغییر رمز</button>
                    </form>
                    <a asp-page="./EditProfile" asp-route-BrandInput="@Model.CurrentUser.BrandName" asp-route-State="EditProfile" style="text-decoration: none">
                        <button class="submit-button" style="margin-top: 10px">تغییر اطلاعات </button>
                    </a>
                </div>
            </div>
        </div>
    }
}
else
{
    <h1 style="text-align: center">Not Authorized</h1>
}